### ISSUE TITLE
Set token via config

### ISSUE THREAD

**Issue by joshuabaker** [flipboxfactory/craft-postmark#6]
It doesn’t appear possible to set the token value via a `postmark.php` config file. Attempting currently results in an error.

**Config**

```php
<?php

return [
    'token' => 'TOKEN_HERE',
];
```

**Error**

```
Call to a member function setAttributes() on null
```

**Comment by joshuabaker** [comment]
Yeah, that’s right.

I was trying to figure out how to do this via the [Mailer Component config](https://docs.craftcms.com/v3/config/#mailer-component). Wondering if that’s an approach here?

**Comment by nateiler** [comment]
I was just drilling into the System Settings and saw that option too.

I'm sure something like this might work:

```php
<?php

return [
    '*' => [
        'components' => [
            'mailer' => function() {
    
                // Get the stored email settings
                $settings = Craft::$app->systemSettings->getEmailSettings();

                // Override the transport adapter class
                $settings->transportSettings['token'] = 'xxx';

                return Craft::createObject(
                    craft\helpers\App::mailerConfig($settings)
                );
            }
        ]
    ],

    'prod' => [
        'components' => [
            'mailer' => function() {

                // Get the stored email settings
                $settings = Craft::$app->systemSettings->getEmailSettings();

                // Override the transport adapter class
                $settings->transportSettings['token'] = 'prod-xxx';

                return Craft::createObject(
                    craft\helpers\App::mailerConfig($settings)
                );
            }
        ]
    ]
];
```
It's not very graceful.

I suppose it's also possible to add a settings model to the plugin and override what's in the database when the Postmark adapter is created.

**Comment by nateiler** [comment]
I don't really like the component config solution, because it implies that you'll always use Postmark.

**Comment by joshuabaker** [comment]
Yeah, I agree. As much as I hate the component config approach, it’s not really for this plugin to address.

Thanks for the responses, dude. 👍

**Comment by joshuabaker** [comment]
Love it! Thanks, Nate. 💯
